INSERT INTO categoria (id, nombre_cat) VALUES ('1', 'Accesoriaso para Vehiculos');
INSERT INTO categoria (id, nombre_cat) VALUES ('2', 'Alimnetos y Bebidas');
INSERT INTO categoria (id, nombre_cat) VALUES ('3', 'Arte y Antiguedades');
INSERT INTO categoria (id, nombre_cat) VALUES ('4', 'Autos, Motos y Otros');
INSERT INTO categoria (id, nombre_cat) VALUES ('5', 'Bebes');
INSERT INTO categoria (id, nombre_cat) VALUES ('6', 'Camaras y Accesorios');
INSERT INTO categoria (id, nombre_cat) VALUES ('7', 'Celulares y telefonía');
INSERT INTO categoria (id, nombre_cat) VALUES ('8', 'Coleccionables y Hobbies');
INSERT INTO categoria (id, nombre_cat) VALUES ('9', 'Computacoón');
INSERT INTO categoria (id, nombre_cat) VALUES ('10', 'Consolas y Video Juegos');
INSERT INTO categoria (id, nombre_cat) VALUES ('11', 'Deportes y Fitness');
INSERT INTO categoria (id, nombre_cat) VALUES ('12', 'Electrodomésticos');
INSERT INTO categoria (id, nombre_cat) VALUES ('13', 'Electrónica, audio y video');
INSERT INTO categoria (id, nombre_cat) VALUES ('14', 'Herraminestas y Construcción');
INSERT INTO categoria (id, nombre_cat) VALUES ('15', 'Insdustrias y Oficinas');
INSERT INTO categoria (id, nombre_cat) VALUES ('16', 'Instrumentos Musicales');
INSERT INTO categoria (id, nombre_cat) VALUES ('17', 'Juegos y Jueguetes');
INSERT INTO categoria (id, nombre_cat) VALUES ('18', 'Libros, Revistas y Comics');
INSERT INTO categoria (id, nombre_cat) VALUES ('19', 'Música y Películas');
INSERT INTO categoria (id, nombre_cat) VALUES ('20', 'Relojes y Joyas');
INSERT INTO categoria (id, nombre_cat) VALUES ('21', 'Salud y Belleza');
INSERT INTO categoria (id, nombre_cat) VALUES ('22', 'Vestuario y Calzado');
INSERT INTO categoria (id, nombre_cat) VALUES ('23', 'Otras Categorías');