INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('1', '1', 'Accesorios de Auto y Camioneta ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('2', '1', 'Accesorios para Motos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('3', '1', 'Audio para Vehículos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('4', '1', 'GPS ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('5', '1', 'Herramientas para Vehículos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('6', '1', 'Limpieza de Vehículos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('7', '1', 'Llantas ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('8', '1', 'Neumáticos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('9', '1', 'Repuestos Autos y Camionetas ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('10', '1', 'Repuestos para Motos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('11', '1', 'Seguridad para Vehículos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('12', '1', 'Service Programado ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('13', '1', 'Tuning y Performance ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('14', '2', 'Bebidas Alcohólicas ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('15', '2', 'Bebidas Energéticas ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('16', '2', 'Bebidas Sin Alcohol ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('17', '2', 'Cigarros ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('18', '2', 'Comestibles ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('19', '2', 'Infusiones ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('20', '2', 'Libros de Cocina ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('21', '3', 'Antigüedades ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('22', '3', 'Arte ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('23', '3', 'Artesanías ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('24', '4', 'Autos de Colección ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('25', '4', 'Autos y Camionetas ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('26', '4', 'Camiones ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('27', '4', 'Maquinaria Pesada ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('28', '4', 'Motos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('29', '4', 'Náutica ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('30', '5', 'Andadores y Vehículos de Bebés ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('31', '5', 'Artículos de Bebé para Baños ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('32', '5', 'Articulos de Maternidad ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('33', '5', 'Chupetes y Mordedores ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('34', '5', 'Comida para Bebés ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('35', '5', 'Corralitos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('36', '5', 'Dormitorio del Bebé ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('37', '5', 'Higiene y Cuidado del Bebé ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('38', '5', 'Juegos y Juguetes para Bebés ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('39', '5', 'Lactancia y Alimentación ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('40', '5', 'Paseo del Bebé ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('41', '5', 'Salud del Bebé ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('42', '5', 'Seguridad para Bebés ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('43', '5', 'Vestuario para Bebés ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('44', '6', 'Accesorios para Cámaras ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('45', '6', 'Cámaras ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('46', '6', 'Cámaras de Video ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('47', '6', 'Cargadores, Baterías y Pilas ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('48', '6', 'Instrumentos Ópticos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('49', '6', 'Marcos de Fotos Digitales ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('50', '6', 'Memorias Digitales ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('51', '6', 'Papel Fotográfico ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('52', '7', 'Accesorios para Celulares ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('53', '7', 'Celulares y Smartphones ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('54', '7', 'Radioaficionados ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('55', '7', 'Repuestos para Celulares ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('56', '7', 'Teléfonos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('57', '8', 'Afiches, Posters y Fotos ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('58', '8', 'Álbumes y Figuritas ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('59', '8', 'Cartas - RPG');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('60', '8', 'Cigarrillos y Afines ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('61', '8', 'Detectores de Metales ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('62', '8', 'Figuras de Acción ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('63', '8', 'Filatelia');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('64', '8', 'Latas, Botellas y Afines');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('65', '8', 'Militaría y Afines');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('66', '8', 'Modelismo');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('67', '8', 'Numismática');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('68', '8', 'Star Wars ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('69', '8', 'Vehículos en Miniatura');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('70', '9', 'Accesorios para Notebooks');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('71', '9', 'All In One');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('72', '9', 'Apple');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('73', '9', 'Cartuchos y Toners');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('74', '9', 'Componentes para PC');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('75', '9', 'Computadores');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('76', '9', 'Discos Duros y Accesorios');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('77', '9', 'DVDs y CDs Vírgenes');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('78', '9', 'Impresoras y Accesorios');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('79', '9', 'Memorias RAM');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('80', '9', 'Mini PCs');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('81', '9', 'Monitores y Proyectores');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('82', '9', 'Netbooks');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('83', '9', 'Notebooks');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('84', '9', 'Palms y PDA´s');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('85', '9', 'Pen Drives');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('86', '9', 'Periféricos y Accesorios de PC');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('87', '9', 'Placas Madre');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('88', '9', 'Procesadores');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('89', '9', 'Redes y Redes Inalámbricas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('90', '9', 'Software');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('91', '9', 'Tablets');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('92', '9', 'Tarjetas de Video');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('93', '9', 'Ultrabooks');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('94', '9', 'UPS y Fuentes');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('95', '10', 'Nintendo');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('96', '10', 'PlayStation');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('97', '10', 'Sega');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('98', '10', 'Tarjetas Prepagas y Membresías');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('99', '10', 'Videojuegos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('100', '10', 'Xbox');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('101', '11', 'Aerobics y Fitness');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('102', '11', 'Artes Marciales y Boxeo');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('103', '11', 'Baseball');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('104', '11', 'Basquetbol');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('105', '11', 'Bicicletas y Ciclismo');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('106', '11', 'Camping y Pesca');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('107', '11', 'Deportes Acuáticos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('108', '11', 'Deportes Extremos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('109', '11', 'Equitación y Polo');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('110', '11', 'Fútbol');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('111', '11', 'Fútbol Americano');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('112', '11', 'Golf');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('113', '11', 'Handball');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('114', '11', 'Hockey');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('115', '11', 'Juegos de Salón');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('116', '11', 'Máquinas de Ejercicios');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('117', '11', 'Patinaje');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('118', '11', 'Rugby');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('119', '11', 'Skates, Scooters y Hoverboards');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('120', '11', 'Ski y Snowboard');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('121', '11', 'Suplementos Alimenticios');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('122', '11', 'Surf, Windsurf y Bodyboard');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('123', '11', 'Tenis, Padel y Squash');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('124', '11', 'Trekking y Montañismo');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('125', '11', 'Vóleibol');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('126', '11', 'Yoga');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('127', '11', 'Zapatillas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('128', '12', 'Climatización');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('129', '12', 'Hornos y Cocinas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('130', '12', 'Lavado y Secado de Ropa');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('131', '12', 'Lavavajillas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('132', '12', 'Pequeños Electrodomésticos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('133', '12', 'Refrigeración');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('134', '13', 'Accesorios para Audio y Video');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('135', '13', 'Audio para el Hogar');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('136', '13', 'Audio Portátil');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('137', '13', 'Audio Profesional / DJs');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('138', '13', 'Calculadoras');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('139', '13', 'Componentes Electrónicos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('140', '13', 'Drones');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('141', '13', 'DVDs y Home Theaters');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('142', '13', 'Fotocopiadoras');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('143', '13', 'GPS');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('144', '13', 'iPod');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('145', '13', 'MP3 Players');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('146', '13', 'MP4 Players');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('147', '13', 'Proyectores y Telones');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('148', '13', 'Seguridad y Vigilancia Hogar');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('149', '13', 'Soportes');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('150', '13', 'Tablets');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('151', '14', 'Construcción');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('152', '14', 'Herramientas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('153', '14', 'Mobiliario para Baños');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('154', '14', 'Muebles de Cocina');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('155', '14', 'Pisos, Puertas y Ventanas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('156', '15', 'Baños');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('157', '15', 'Cocina');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('158', '15', 'Comedor');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('159', '15', 'Decoración');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('160', '15', 'Dormitorio');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('161', '15', 'Iluminación para el Hogar');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('162', '15', 'Lavadero y Limpieza');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('163', '15', 'Living');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('164', '15', 'Seguridad para el Hogar');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('165', '15', 'Terraza y Jardín');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('166', '16', 'Balanzas Comerciales');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('167', '16', 'Equipamientos Médicos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('168', '16', 'Fuentes de Energía');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('169', '16', 'Gastronomía');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('170', '16', 'Industria Agrícola y Forestal');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('171', '16', 'Industria Automotriz');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('172', '16', 'Industria Textil');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('173', '16', 'Oficinas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('174', '16', 'Seguridad Industrial');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('175', '17', 'Amplificadores');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('176', '17', 'Bajos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('177', '17', 'Baterías y Percusión');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('178', '17', 'Controladores Midi');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('179', '17', 'Efectos de Sonido');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('180', '17', 'Flautas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('181', '17', 'Guitarras');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('182', '17', 'Micrófonos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('183', '17', 'Saxos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('184', '17', 'Teclados y Pianos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('185', '17', 'Violines');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('186', '18', 'Cartas y Juegos de Rol');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('187', '18', 'Figuras de Acción');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('188', '18', 'Juegos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('189', '18', 'Juegos de Aire Libre y Agua');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('190', '18', 'Juguetes');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('191', '18', 'Modelismo');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('192', '18', 'Muñecas y Accesorios');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('193', '18', 'Star Wars');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('194', '18', 'Vehículos en Miniatura');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('195', '18', 'Vehículos para Niños');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('196', '19', 'Comics');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('197', '19', 'Libros');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('198', '19', 'Revistas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('199', '20', 'Exhibidores y Organizadores');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('200', '20', 'Gemelos y Colleras');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('201', '20', 'Joyería');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('202', '20', 'Lápices y plumas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('203', '20', 'Llaveros');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('204', '20', 'Relojes');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('205', '21', 'Cuidado de la Piel');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('206', '21', 'Cuidado del Cabello');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('207', '21', 'Cuidado del Cuerpo');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('208', '21', 'Cuidado Dental');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('209', '21', 'Cuidado para Manos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('210', '21', 'Equipamientos Médicos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('211', '21', 'Lentes');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('212', '21', 'Maquillaje');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('213', '21', 'Perfumes y Fragancias');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('214', '21', 'Vitaminas y Nutrición');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('215', '22', 'Accesorios de Moda');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('216', '22', 'Bermudas y Shorts');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('217', '22', 'Blazers');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('218', '22', 'Blusas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('219', '22', 'Bolsos, Carteras y Mochilas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('220', '22', 'Calzados');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('221', '22', 'Camisas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('222', '22', 'Chalecos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('223', '22', 'Chaquetas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('224', '22', 'Corset');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('225', '22', 'Disfraces');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('226', '22', 'Faldas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('227', '22', 'Lentes');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('228', '22', 'Pantalones y Jeans');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('229', '22', 'Parkas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('230', '22', 'Pijamas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('231', '22', 'Poleras');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('232', '22', 'Polerones');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('233', '22', 'Ropa Interior y Lenceria');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('234', '22', 'Sweaters');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('235', '22', 'Trajes');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('236', '22', 'Trajes de baño');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('237', '22', 'Vestidos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('238', '22', 'Vestuario para Bebés');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('239', '22', 'Zapatillas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('240', '23', 'Adultos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('241', '23', 'Artículos de Cordonería');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('242', '23', 'Baños Químicos');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('243', '23', 'Cotillón y Fiestas');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('244', '23', 'Cuentas y Membresías');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('245', '23', 'Esoterismo ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('246', '23', 'Sepulturas ');
INSERT INTO subcategoria (id,categoria_id, nombre_sub) VALUES ('247', '23', 'Tatuajes ');